---
script: bundle exec rake

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.2
  - jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: always

cache: bundler
