---
image: Visual Studio 2017

version: "{build}"

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-ragel"
  - SET PATH=C:\msys64\mingw64\bin;%PATH%
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle install --retry 3

build: off

before_test:
  - ragel --version
  - ruby --version
  - gem --version
  - bundle --version

test_script:
  - rake

environment:
  matrix:
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"

skip_tags: true

notifications:
  -
    provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
